#!/usr/bin/env bash
# Installer for vault (Termux).
# Run with:  bash install.sh
# Never touches ~/.vault (your secrets are preserved across upgrades).
set -euo pipefail

PREFIX="${PREFIX:-/data/data/com.termux/files/usr}"
BIN_DIR="$PREFIX/bin"
SHARE_DIR="$PREFIX/share/vault"
REPO_DIR="$(cd "$(dirname "$0")" && pwd)"

BASH_BIN="$PREFIX/bin/bash"
PYTHON_BIN="$PREFIX/bin/python3"

die() { printf '✗ %s\n' "$*" >&2; exit 1; }
info() { printf '%s\n' "$*"; }

install_deps() {
    if [ "${VAULT_SKIP_DEPS:-}" = "1" ]; then
        info "Skipping dependency install (VAULT_SKIP_DEPS=1)."
        return 0
    fi
    if ! command -v pkg >/dev/null 2>&1; then
        info "⚠ 'pkg' not found; skipping dependency install (non-Termux?)."
        return
    fi
    info "Installing dependencies (python, python-pynacl, sqlite, fzf, termux-api)..."
    pkg install -y python python-pynacl sqlite fzf termux-api >/dev/null 2>&1 || \
        info "⚠ Some packages failed to install; check manually."
}

check_runtime_deps() {
    local missing=0
    command -v python3 >/dev/null 2>&1 || { info "⚠ python3 not found"; missing=1; }
    command -v fzf >/dev/null 2>&1 || { info "⚠ fzf not found (interactive selection disabled)"; missing=1; }
    command -v termux-clipboard-set >/dev/null 2>&1 || \
        { info "⚠ termux-clipboard-set not found (install Termux:API app + termux-api)"; missing=1; }
    if python3 -c "import nacl" >/dev/null 2>&1; then :; else
        info "⚠ python-pynacl missing (run: pkg install python-pynacl)"; missing=1
    fi
    return "$missing"
}

rewrite_shebang() {
    local file="$1" interp="$2"
    [ -f "$file" ] || return 0
    local tmp
    tmp="$(mktemp "${TMPDIR:-/tmp}/vaultshebang.XXXXXX")"
    { printf '#!%s\n' "$interp"; tail -n +2 "$file"; } > "$tmp"
    cat "$tmp" > "$file"
    rm -f "$tmp"
}

do_install() {
    [ -f "$REPO_DIR/bin/vault" ] || die "bin/vault not found next to install.sh"
    [ -f "$REPO_DIR/lib/vaultd.py" ] || die "lib/vaultd.py not found next to install.sh"

    install_deps || true

    info "Installing to $SHARE_DIR ..."
    rm -rf "$SHARE_DIR"
    mkdir -p "$SHARE_DIR"
    cp -R "$REPO_DIR/bin" "$SHARE_DIR/bin"
    cp -R "$REPO_DIR/lib" "$SHARE_DIR/lib"

    # Absolute shebangs are required: Termux has no /usr/bin/env.
    rewrite_shebang "$SHARE_DIR/bin/vault" "$BASH_BIN"
    rewrite_shebang "$SHARE_DIR/lib/vaultd.py" "$PYTHON_BIN"
    rewrite_shebang "$SHARE_DIR/lib/vault_client.py" "$PYTHON_BIN"

    chmod 755 "$SHARE_DIR/bin/vault"
    chmod 755 "$SHARE_DIR/lib/vaultd.py" "$SHARE_DIR/lib/vault_client.py"
    chmod 644 "$SHARE_DIR/lib/common.py" "$SHARE_DIR/lib/crypto_vault.py" "$SHARE_DIR/lib/db_vault.py"

    # Launcher shim
    cat > "$BIN_DIR/vault" <<EOF
#!$BASH_BIN
# vault launcher shim (generated by install.sh)
export VAULT_DIR="\${VAULT_DIR:-\$HOME/.vault}"
export PYTHONPATH="$SHARE_DIR/lib\${PYTHONPATH:+:\$PYTHONPATH}"
exec "$SHARE_DIR/bin/vault" "\$@"
EOF
    chmod 755 "$BIN_DIR/vault"

    info "✓ Installed: $BIN_DIR/vault  (data: ~/.vault)"
    if ! check_runtime_deps; then
        info "⚠ Install finished with missing runtime dependencies (see above)."
    fi
    info "Try:  vault help"
}

do_uninstall() {
    local purge="${1:-}"
    rm -f "$BIN_DIR/vault"
    rm -rf "$SHARE_DIR"
    info "✓ Removed $BIN_DIR/vault and $SHARE_DIR"
    if [ "$purge" = "--purge" ]; then
        rm -rf "${VAULT_DIR:-$HOME/.vault}"
        info "✓ Removed vault data directory (--purge)"
    else
        info "Vault data left intact at ~/.vault (use --purge to remove)."
    fi
}

case "${1:-}" in
    --uninstall)
        do_uninstall "${2:-}"
        ;;
    --help|-h)
        info "Usage: bash install.sh [--uninstall [--purge]]"
        ;;
    *)
        do_install
        ;;
esac
